### ISSUE TITLE
Use of itoa() on TI platforms

### ISSUE THREAD

**Issue by speters** [grblHAL/Plugin_OpenPNP#2]
While playing around with plugins on my _TM4C1294XL_, I came over a compile error in
https://github.com/grblHAL/Plugin_OpenPNP/blob/422f7a49b2c9da60910a896278f0a4efeddc71b1/openpnp.c#L155
due to it not being a standard function and not contained in TI's _stdlib.h_

Quick fix `ltoa()`?

**Comment by terjeio** [comment]
> Quick fix ltoa()?

That breaks other drivers...

I added a macro symbol for itoa() in CCS:

![image](https://user-images.githubusercontent.com/20260062/202772998-426966e0-bd2d-4eff-b4b6-88aba491d99d.png)

Way to fix it?
